const assert = require('node:assert/strict')
const fs = require('node:fs')
const ts = require('typescript')
require.extensions['.ts'] = (module, filename) => module._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText, filename)
const storage = new Map()
global.window = { localStorage: { getItem: key => storage.get(key) || null, setItem: (key, value) => storage.set(key, value) } }
global.document = { cookie: '' }
global.fetch = () => { throw new Error('Demo must never call the network') }
const { apiFetch } = require('../lib/api-fetch.ts')
const { mockClient: client } = require('../lib/mock-client.ts')
const { readStore, DEMO_EMAIL, DEMO_PASSWORD } = require('../lib/mock-store.ts')
const request = (url, method, body) => apiFetch(url, { method, body: body ? JSON.stringify(body) : undefined })
async function run() {
  const posts = await (await apiFetch('/api/posts')).json()
  assert.equal(posts.length, 6)
  assert.equal((await request('/api/posts', 'POST', {})).status, 401)
  assert.ok((await client.auth.signInWithPassword({email: DEMO_EMAIL, password: 'wrong'})).error)
  assert.equal((await client.auth.signInWithPassword({email: DEMO_EMAIL, password: DEMO_PASSWORD})).error, null)
  assert.match(document.cookie, /camerocare-demo-session=1/)
  const filtered = await (await apiFetch('/api/posts?type=offer&category=Tech%20Support')).json()
  assert.equal(filtered.length, 1)
  assert.equal(filtered[0].type, 'HELP_OFFER')
  const post = await (await request('/api/posts', 'POST', { title: 'Test request', description: 'A local test', type: 'HELP_REQUEST', categories: ['Volunteering'] })).json()
  assert.ok(readStore().tables.posts.some(p => p.id === post.id))
  assert.equal((await request('/api/posts/demo-post-1', 'DELETE')).status, 403)
  await request('/api/posts/demo-post-1/bookmark', 'POST', { action: 'bookmark' })
  await request('/api/posts/demo-post-1/bookmark', 'POST', { action: 'bookmark' })
  assert.equal(readStore().tables.bookmarks.length, 1)
  assert.equal((await (await apiFetch('/api/posts/bookmarked')).json()).length, 1)
  await request('/api/posts/demo-post-1/bookmark', 'POST', { action: 'unbookmark' })
  assert.equal(readStore().tables.bookmarks.length, 0)
  const result = await (await request('/api/posts/demo-post-2/request-help', 'POST', { message: 'I would like to learn' })).json()
  const repeated = await (await request('/api/posts/demo-post-2/request-help', 'POST', {})).json()
  assert.equal(result.conversationId, repeated.conversationId)
  let delivered
  const channel = client.channel('test').on('postgres_changes', { event: 'INSERT', table: 'messages', filter: `conversation_id=eq.${result.conversationId}` }, event => { delivered = event.new }).subscribe()
  await client.from('messages').insert({ conversation_id: result.conversationId, sender_id: 'demo-user', message_text: 'Hello offline', is_read: false })
  assert.equal(delivered.message_text, 'Hello offline')
  const messages = await client.from('messages').select('*').eq('conversation_id', result.conversationId)
  assert.equal(messages.data.length, 2)
  await client.removeChannel(channel)
  await request('/api/users/demo-user', 'PUT', { name: 'Edited Demo', email: 'edited@camerocare.local' })
  assert.equal((await (await apiFetch('/api/users/demo-user')).json()).name, 'Edited Demo')
  await client.auth.signOut()
  assert.equal((await client.auth.getSession()).data.session, null)
  assert.equal((await client.auth.signInWithPassword({email: 'edited@camerocare.local', password: DEMO_PASSWORD})).error, null)
  await request(`/api/posts/${post.id}`, 'DELETE')
  assert.equal(readStore().tables.posts.some(p => p.id === post.id), false)
  await client.auth.signUp({ email: 'new@demo.local', password: 'Demo123!', options: { data: { name: 'New Demo' } } })
  await client.auth.signOut()
  assert.equal((await client.auth.signInWithPassword({email: 'new@demo.local', password: 'Demo123!'})).error, null)
  assert.equal((await client.auth.getSession()).data.session.user.user_metadata.name, 'New Demo')
  console.log('Mock flow checks passed: guest browsing, login/signup/logout, filtering, post creation/deletion, ownership, bookmarks, conversations, live message events, profiles, persistence; no network calls.')
}
run().catch(error => { console.error(error); process.exitCode = 1 })
